### ISSUE TITLE
ideas for creating plugins

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-plugins-idea#6]
- [ ] [posthtml-limit-line](https://github.com/posthtml/posthtml-render/issues/3)
- [ ] [posthtml-hbs](https://github.com/posthtml/posthtml/issues/193)
- [ ] [posthtml-yaml-vars](https://github.com/posthtml/posthtml-extend/issues/10)
- [ ] [posthtml-redirect-lowercase-urls](https://github.com/posthtml/posthtml-plugins/issues/18)
- [ ] [posthtml-icono](https://github.com/posthtml/posthtml-plugins/issues/19)
